FROM python:3.9-slim

WORKDIR /app

COPY test_authorization.py /app

# Installer une version spécifique de pip
RUN pip install pip==23.0.1 && \
    pip install requests

CMD ["python", "test_authorization.py"]
